services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${HOMEPAGE_VERSION:-latest}
    network_mode: ${NETWORK_MODE:-bridge}
    env_file: environment.d/homepage.env
    ports:
      - ${HOMEPAGE_PORT:-3000}:3000
    volumes:
      - ${HOMEPAGE_CONFIG_VOLUME:-./volumes/homepage}:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
